### PR TITLE
Feature 1

### PR DESCRIPTION
**Pull request by Abass-rashid**
I have added the linters files and hidden my node modules in the .gitignore file please review and let me know what you think.
1. removed the linters errors
2. Added the suggested microverse template
3.  removed node-modules 
4. documented my README file in professional way

### CODE REVIEW

**Review by ShahierNashaat — CHANGES_REQUESTED** [review]
Hi @Abass-rashid , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Please remove the node_modules folder.
- [ ] Please remove test.md file.
- [ ] Pull Request should have a descriptive title telling you what changes are inside.
- [ ] Pull Request should have a summary describing introduced changes in more detail.
- [ ] Please make sure that there is no linters errors.
- [ ] Please use Microverse README template.

## Optional suggestions
- [ ] [Optional] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section').

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abass-rashid** [comment]
I have rectified all my problems and fixed the bugs please have a look to it .

**Comment by Abass-rashid** [comment]
I have documented my README file in a professional and descriptive way please take a look t

**Comment by Abass-rashid** [comment]
have fixed my bug please take your time to review my code

**Review by MrRamoun — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @Abass-rashid 👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse 🌐.

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ Pull Request has a descriptive title and summary.
- ✔️ The `README.md` file is descriptive
- ✔️ Removed the `node_modules` as requested in the previous review.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **Twitter**: [@ramoun16](https://twitter.com/ramoun16)
- This is My **Slack**: [Ramoun](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
